### ISSUE TITLE
Raphael needs to be added to team

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/zurich.rustfest.eu#2]
Please add [here](https://github.com/RustFestEU/zurich.rustfest.eu/blob/gh-pages/_data/team.yml)

- [x] Picture [here](https://github.com/RustFestEU/zurich.rustfest.eu/tree/gh-pages/assets/team).
- [x]  Social links you are comfortable with sharing

**Comment by gandro** [comment]
cc @rnestler
