### ISSUE TITLE
Accessibility Statement

### ISSUE THREAD

**Issue by Hoverbear** [RustFestEU/zurich.rustfest.eu#3]
The accessibility statement needs to be updated. We talked at the meeting that the [Berlin one](https://github.com/RustFestEU/2016.rustfest.eu/blob/gh-pages/accessibility.md) will be accurate for Zurich

**Comment by katsel** [comment]
What's so difficult about providing non-gendered restrooms? One just decides to put a sign at the doors of one or more existing restrooms ([there is a template for that](https://github.com/RustFestEU/resources)). And make sure that the urinals cannot be used (that'd be awkward for many people).
Voilà! Non-gendered toilets that gendered and non-gendered people alike can use.

**Comment by skade** [comment]
The actual implementation is not the problem.

We don't have exclusive access to the venue and there's a parallel event, so we can't just put signs up.

**Comment by katsel** [comment]
One could try talking to the venue or the organizers of that parallel event (if known) to find a solution.

**Comment by skade** [comment]
The question has already been posted to the venue, but we are still waiting for a conclusive answer.

**Comment by dns2utf8** [comment]
We heard back from the venue. There will be a non-genered toilet.

**Comment by skade** [comment]
As per our discussion in the chat, I don't think the statement from the venue quite cuts it.

**Comment by skade** [comment]
As per our discussion in the chat, I don't think the statement from the venue quite cuts it. Let's circle around.

**Comment by skade** [comment]
Sorry for my previous statement, there was an internal miscommunication, I should have asked before stating that in public.

There will be proper non-gendered toilets.

Apologies to @dns2utf8.

**Comment by skade** [comment]
Clarified through #30
