### ISSUE TITLE
Update sponsorship page

### ISSUE THREAD

**Issue by gandro** [RustFestEU/zurich.rustfest.eu#9]
The current page still shows the old sponsors for Kyiv. Do we hide this page until we officially announce the sponsors for Zurich? Do we link to sponsorship packages?

**Comment by Hoverbear** [comment]
We should put up the sponsors we know about as soon as we can, but we can hide it until then!

**Comment by dns2utf8** [comment]
This was resolved with #26, #27 and #28.
